DEFAULT_AGENT_MODEL = "gpt-4o-mini"

INTENT_AGENT_MODEL = DEFAULT_AGENT_MODEL
GENERAL_AGENT_MODEL = DEFAULT_AGENT_MODEL
HSO_AGENT_MODEL = DEFAULT_AGENT_MODEL
SWEATY_AGENT_MODEL = DEFAULT_AGENT_MODEL
AGGREGATOR_AGENT_MODEL = DEFAULT_AGENT_MODEL
